# Import Library

In [32]:
import tensorflow as tf
import numpy as np

# Random Tensor

In [33]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=4)
print(random_tensor.numpy())

[[-1.4347187   0.9239041   0.4699213   0.6724554   0.92193186]
 [ 0.5830776  -0.29723737  0.5824093  -1.0757695  -0.12024921]
 [-0.22192276  0.847953   -0.20324574  0.00324441 -1.1847441 ]
 [ 1.0604854  -0.5577433  -0.7471574   0.7615613  -0.64336294]
 [ 0.97187966 -0.25947025 -0.5108813   0.8646555   0.92503107]]


# Prime Tensor

In [34]:
prime = [[2, 3, 5, 7, 11],
         [13, 17, 19, 23, 29],
         [31, 37, 41, 43, 47],
         [53, 59, 61, 71, 73],
         [79, 83, 89, 97, 101]]

prime_tensor = tf.constant(prime, dtype=tf.float32)
print(prime_tensor.numpy())

[[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


# Dimensi Tensor

In [35]:
#Random
print(random_tensor.shape)

(5, 5)


In [36]:
#Prime
print(prime_tensor.shape)

(5, 5)


# Perhitungan Aritmatika

### Penambahan

In [38]:
print(tf.add(random_tensor, prime_tensor).numpy())

[[  0.5652813   3.9239042   5.469921    7.6724553  11.921932 ]
 [ 13.583077   16.702763   19.582409   21.92423    28.879751 ]
 [ 30.778078   37.847954   40.796753   43.003246   45.815254 ]
 [ 54.060486   58.442257   60.252842   71.76156    72.356636 ]
 [ 79.97188    82.74053    88.48912    97.864655  101.92503  ]]


### Pengurangan

In [39]:
print(tf.subtract(random_tensor, prime_tensor).numpy())

[[  -3.4347186   -2.0760958   -4.530079    -6.3275447  -10.078068 ]
 [ -12.416923   -17.297237   -18.417591   -24.07577    -29.120249 ]
 [ -31.221922   -36.152046   -41.203247   -42.996754   -48.184746 ]
 [ -51.939514   -59.557743   -61.747158   -70.23844    -73.643364 ]
 [ -78.02812    -83.25947    -89.51088    -96.135345  -100.07497  ]]


### Perkalian

In [40]:
print(tf.multiply(random_tensor, prime_tensor).numpy())

[[ -2.8694375    2.7717123    2.3496065    4.7071877   10.141251  ]
 [  7.580009    -5.0530353   11.065777   -24.742699    -3.4872272 ]
 [ -6.8796053   31.374262    -8.333076     0.13950984 -55.682972  ]
 [ 56.205723   -32.906857   -45.576603    54.07085    -46.965496  ]
 [ 76.778496   -21.536032   -45.468437    83.87158     93.42814   ]]


### Pembagian

In [41]:
print(tf.divide(random_tensor, prime_tensor).numpy())

[[-7.1735936e-01  3.0796805e-01  9.3984261e-02  9.6065052e-02
   8.3811991e-02]
 [ 4.4852123e-02 -1.7484551e-02  3.0653123e-02 -4.6772588e-02
  -4.1465247e-03]
 [-7.1587986e-03  2.2917649e-02 -4.9572131e-03  7.5451513e-05
  -2.5207322e-02]
 [ 2.0009158e-02 -9.4532762e-03 -1.2248482e-02  1.0726215e-02
  -8.8131912e-03]
 [ 1.2302274e-02 -3.1261477e-03 -5.7402393e-03  8.9139743e-03
   9.1587231e-03]]


### Logarithm

In [42]:
print(tf.math.log(random_tensor, prime_tensor).numpy())

[[        nan -0.07914697 -0.7551901  -0.39681953 -0.08128396]
 [-0.53943497         nan -0.5405818          nan         nan]
 [        nan -0.16493003         nan -5.73082            nan]
 [ 0.05872669         nan         nan -0.27238464         nan]
 [-0.02852329         nan         nan -0.14542411 -0.07792795]]


### Perpangkatan

In [43]:
print(tf.pow(random_tensor, prime_tensor).numpy())

[[ 2.0584178e+00  7.8864348e-01  2.2915304e-02  6.2179077e-02
   4.0896589e-01]
 [ 9.0041506e-04 -1.1034633e-09  3.4620876e-05 -5.3646650e+00
  -2.1008009e-27]
 [-5.3982986e-21  2.2374652e-03 -4.2548072e-29  0.0000000e+00
  -2.8863860e+03]
 [ 2.2477499e+01 -1.0955391e-15 -1.8973090e-08  3.9906580e-09
  -1.0406170e-14]
 [ 1.0504781e-01  0.0000000e+00 -1.0976931e-26  7.4779274e-07
   3.8175800e-04]]


### Modulus

In [44]:
print(tf.math.floormod(random_tensor, prime_tensor).numpy())

[[5.6528127e-01 9.2390412e-01 4.6992129e-01 6.7245537e-01 9.2193186e-01]
 [5.8307761e-01 1.6702763e+01 5.8240932e-01 2.1924231e+01 2.8879751e+01]
 [3.0778078e+01 8.4795302e-01 4.0796753e+01 3.2444149e-03 4.5815254e+01]
 [1.0604854e+00 5.8442257e+01 6.0252842e+01 7.6156127e-01 7.2356636e+01]
 [9.7187966e-01 8.2740532e+01 8.8489120e+01 8.6465549e-01 9.2503107e-01]]


# Nilai Maksimal dan Minimal

In [45]:
#max
print(tf.reduce_max(random_tensor).numpy())

1.0604854


In [46]:
#min
print(tf.reduce_min(random_tensor).numpy())

-1.4347187


# Tensor Concatenation

In [47]:
print(tf.concat([random_tensor, prime_tensor], axis=0).numpy())

[[-1.4347187e+00  9.2390412e-01  4.6992129e-01  6.7245537e-01
   9.2193186e-01]
 [ 5.8307761e-01 -2.9723737e-01  5.8240932e-01 -1.0757695e+00
  -1.2024921e-01]
 [-2.2192276e-01  8.4795302e-01 -2.0324574e-01  3.2444149e-03
  -1.1847441e+00]
 [ 1.0604854e+00 -5.5774331e-01 -7.4715739e-01  7.6156127e-01
  -6.4336294e-01]
 [ 9.7187966e-01 -2.5947025e-01 -5.1088130e-01  8.6465549e-01
   9.2503107e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  7.1000000e+01
   7.3000000e+01]
 [ 7.9000000e+01  8.3000000e+01  8.9000000e+01  9.7000000e+01
   1.0100000e+02]]


In [48]:
print(tf.concat([random_tensor, prime_tensor], axis=1).numpy())

[[-1.4347187e+00  9.2390412e-01  4.6992129e-01  6.7245537e-01
   9.2193186e-01  2.0000000e+00  3.0000000e+00  5.0000000e+00
   7.0000000e+00  1.1000000e+01]
 [ 5.8307761e-01 -2.9723737e-01  5.8240932e-01 -1.0757695e+00
  -1.2024921e-01  1.3000000e+01  1.7000000e+01  1.9000000e+01
   2.3000000e+01  2.9000000e+01]
 [-2.2192276e-01  8.4795302e-01 -2.0324574e-01  3.2444149e-03
  -1.1847441e+00  3.1000000e+01  3.7000000e+01  4.1000000e+01
   4.3000000e+01  4.7000000e+01]
 [ 1.0604854e+00 -5.5774331e-01 -7.4715739e-01  7.6156127e-01
  -6.4336294e-01  5.3000000e+01  5.9000000e+01  6.1000000e+01
   7.1000000e+01  7.3000000e+01]
 [ 9.7187966e-01 -2.5947025e-01 -5.1088130e-01  8.6465549e-01
   9.2503107e-01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01  1.0100000e+02]]



# Tensor Sorting

In [49]:
print(tf.sort(random_tensor, direction='DESCENDING').numpy()) # axis=1

[[ 0.9239041   0.92193186  0.6724554   0.4699213  -1.4347187 ]
 [ 0.5830776   0.5824093  -0.12024921 -0.29723737 -1.0757695 ]
 [ 0.847953    0.00324441 -0.20324574 -0.22192276 -1.1847441 ]
 [ 1.0604854   0.7615613  -0.5577433  -0.64336294 -0.7471574 ]
 [ 0.97187966  0.92503107  0.8646555  -0.25947025 -0.5108813 ]]


In [50]:
print(tf.sort(random_tensor, direction='DESCENDING', axis=0).numpy())

[[ 1.0604854   0.9239041   0.5824093   0.8646555   0.92503107]
 [ 0.97187966  0.847953    0.4699213   0.7615613   0.92193186]
 [ 0.5830776  -0.25947025 -0.20324574  0.6724554  -0.12024921]
 [-0.22192276 -0.29723737 -0.5108813   0.00324441 -0.64336294]
 [-1.4347187  -0.5577433  -0.7471574  -1.0757695  -1.1847441 ]]


In [51]:
print(tf.sort(prime_tensor, direction='DESCENDING').numpy()) # axis=1

[[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]]


In [52]:
print(tf.sort(prime_tensor, direction='DESCENDING', axis=0).numpy())

[[ 79.  83.  89.  97. 101.]
 [ 53.  59.  61.  71.  73.]
 [ 31.  37.  41.  43.  47.]
 [ 13.  17.  19.  23.  29.]
 [  2.   3.   5.   7.  11.]]
